//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Appointment
{
    public int App_ID { get; set; }
    public string App_Date { get; set; }
    public string Time { get; set; }
    public string K_name { get; set; }
    public string K_DOB { get; set; }
    public string Parent_name { get; set; }
    public string Phone_num { get; set; }
    public string D_name { get; set; }
    public int K_ID { get; set; }
    public int D_ID { get; set; }

    public virtual Doctor Doctor { get; set; }
    public virtual Kid Kid { get; set; }
}

public partial class Comment
{
    public int Com_ID { get; set; }
    public string Text { get; set; }
    public string Com_Date { get; set; }
    public int U_ID { get; set; }
    public int Vid_ID { get; set; }

    public virtual user user { get; set; }
    public virtual Video Video { get; set; }
}

public partial class Cours
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cours()
    {
        this.Videos = new HashSet<Video>();
    }

    public int Co_ID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public int Vid_ID { get; set; }

    public virtual Video Video { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Video> Videos { get; set; }
}

public partial class Doctor
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Doctor()
    {
        this.Appointments = new HashSet<Appointment>();
        this.Sessions = new HashSet<Session>();
    }

    public int D_ID { get; set; }
    public string F_name { get; set; }
    public string L_name { get; set; }
    public string DOB { get; set; }
    public string Gender { get; set; }
    public string National_ID { get; set; }
    public string Phone_num { get; set; }
    public string Experience { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Appointment> Appointments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Session> Sessions { get; set; }
}

public partial class Kid
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Kid()
    {
        this.Appointments = new HashSet<Appointment>();
        this.Sessions = new HashSet<Session>();
    }

    public int K_ID { get; set; }
    public string K_name { get; set; }
    public string DOB { get; set; }
    public string Gender { get; set; }
    public string Address { get; set; }
    public string Medical_conditions { get; set; }
    public string Medecations { get; set; }
    public string Chife_complaint { get; set; }
    public int U_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Appointment> Appointments { get; set; }
    public virtual user user { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Session> Sessions { get; set; }
}

public partial class Session
{
    public int S_ID { get; set; }
    public string S_Date { get; set; }
    public string Medical_Diagnosis { get; set; }
    public int D_ID { get; set; }
    public int K_ID { get; set; }

    public virtual Doctor Doctor { get; set; }
    public virtual Kid Kid { get; set; }
}

public partial class Test
{
    public int Te_ID { get; set; }
    public string Score { get; set; }
    public string Te_Date { get; set; }
    public int U_ID { get; set; }

    public virtual user user { get; set; }
}

public partial class user
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public user()
    {
        this.Comments = new HashSet<Comment>();
        this.Kids = new HashSet<Kid>();
        this.Tests = new HashSet<Test>();
    }

    public int U_ID { get; set; }
    public string F_namre { get; set; }
    public string L_name { get; set; }
    public string DOB { get; set; }
    public string Gender { get; set; }
    public string Phone_num { get; set; }
    public string Email { get; set; }
    public string Password { get; set; }
    public string Permissions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Kid> Kids { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Test> Tests { get; set; }
}

public partial class Video
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Video()
    {
        this.Comments = new HashSet<Comment>();
        this.Courses = new HashSet<Cours>();
    }

    public int Vid_ID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string Upload_Date { get; set; }
    public string Views { get; set; }
    public int Co_ID { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Comment> Comments { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cours> Courses { get; set; }
    public virtual Cours Cours { get; set; }
}
