//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class DatabaseEntities3 : DbContext
{
    public DatabaseEntities3()
        : base("name=DatabaseEntities3")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Accounts> Accounts { get; set; }
    public virtual DbSet<Appointment> Appointment { get; set; }
    public virtual DbSet<Article> Article { get; set; }
    public virtual DbSet<Courses> Courses { get; set; }
    public virtual DbSet<Doctor> Doctor { get; set; }
    public virtual DbSet<Kids> Kids { get; set; }
    public virtual DbSet<Posts> Posts { get; set; }
    public virtual DbSet<Prescriptions> Prescriptions { get; set; }
    public virtual DbSet<Sessions> Sessions { get; set; }
    public virtual DbSet<Videos> Videos { get; set; }
    public virtual DbSet<users> users { get; set; }
}
